### ISSUE TITLE
Proper view to posts

### ISSUE THREAD

**Issue by lordadamson** [lordadamson/weresick#1]
Currently the posts are displayed in a naive way. a table that displays the user and posts.

We need a nice view that shows a clean frame around each post.
* Showing the username which links to his journal.
* Showing the content of the post.
* A button that only shows up when the user hovers over the post. This button displays a menu that has edit, delete and report.

**Comment by AhmedKamal20** [comment]
@lordadamson 
Is the post has created date ? , and if so , how i access it in the views ?

**Comment by lordadamson** [comment]
Yes the post has a created-at date, however it's not needed at the moment. I want to let the interface be as minimalist as possible. I'll let you know when we need to add it.
