### ISSUE TITLE
A notification system

### ISSUE THREAD

**Issue by lordadamson** [lordadamson/weresick#15]
This needs to be extensible to handle different kinds of events

**Comment by lordadamson** [comment]
consider using [this beast](https://github.com/fenos/Notifynder)

**Comment by Ahmed-Badawy** [comment]
no, i can handle it. 
will use angular. 
just create the backend functionality & i will ajax it every 10 secs.

**Comment by lordadamson** [comment]
do you or do you not recommend using [Notifynder](https://github.com/fenos/Notifynder)?
