### ISSUE TITLE
load google fonts locally

### ISSUE THREAD

**Issue by lordadamson** [lordadamson/weresick#6]
referencing google fonts through the internet is undesired for development purposes.
In case there is no internet. we don't need the whole website to blow up when devs are trying to work on it offline.

thus this line in `app.blade.php` is a problem: `<link href="https://fonts.googleapis.com/css?family=Amiri" rel="stylesheet">`

**Comment by YahyaElharony** [comment]
You can fix it by 2 methods : 
1- Download the desired font in your case it is Amiri font you can download it from the link below 
https://www.google.com/fonts#UsePlace:use/Collection:Amiri
2- Go to your style.css file and add these lines
@font-face {
    font-family: Amiri;
    src: url(../fonts/YOURFONTNAME.Extention);
}
Now your font is locally seen, you can use it directly like this
h1,h2,h3,h4,h5,h6 {
 font-family: Amiri, ALTERNATE Font 1, ALTERNATE Font 2;
}
You can add other elements after h6, like input,span,div .. etc.

**Comment by lordadamson** [comment]
@YahyaElharony why don't you do it yourself so that the commit would have your name on it?

**Comment by YahyaElharony** [comment]
It was my first time to use github and I don't know how to do that myself
:D.
I will definitely learn how to deal with github ^^

**Comment by lordadamson** [comment]
good luck with that :))
consider completing this challenge if you wanna learn about git
https://github.com/Open-Source-Community/iusegit
